name: Continuous Integration

on:
  push:
    branches: [main] # Especifica em quais branches o workflow será executado
  pull_request:
    branches: [main] # Adiciona execução em pull requests

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Usa aspas para garantir que seja tratado como string

      - name: Install dependencies
        run: npm ci # Usa 'npm ci' em vez de 'npm install' para instalações em CI

      - name: Build
        run: npm run build

      - name: Deploy to local server
        uses: appleboy/ssh-action@master
        with:
          host: 172.25.100.154
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/sistemas
            rm -rf *
            cp -R dist/* .
            sudo systemctl restart apache2
